apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: utes-website-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - utes.ir
    secretName: utes-tls
  rules:
  - host: utes.ir
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: utes-website-service
            port:
              number: 80

